package com.oxyzen.thesetofsevenworlds;

import com.oxyzen.framework.Music;
import com.oxyzen.framework.Pixmap;
import com.oxyzen.framework.Sound;

public class Assets {
    public static Pixmap background;
    public static Pixmap backgroundmanypieces;
    public static Pixmap backgroundmoregrass;
    public static Pixmap backgroundflower;
    public static Pixmap backgroundgrassdash;
    public static Pixmap backgroundpeaceone;
    public static Pixmap backgroundpeacetwo;
    public static Pixmap aboutauthor;
    public static Pixmap logo;
    public static Pixmap pad;
    public static Pixmap trackpad;
    public static Pixmap trackpadup;
    public static Pixmap trackpaddown;
    public static Pixmap trackpadleft;
    public static Pixmap trackpadright;
    public static Pixmap oeufPlat1;
    public static Pixmap oeufPlat2;
    public static Pixmap oeufPlat3;
    public static Pixmap coquille;
    public static Pixmap oeufDur;
    public static Pixmap troisOeufs;
    public static Pixmap deuxOeufs;
    public static Pixmap deuxOeufsCouches;
    public static Pixmap unOeuf;
    public static Pixmap piwiBack;
    public static Pixmap gameOver;
    public static Pixmap gameovertext;
    public static Pixmap mainMenu;
    public static Pixmap soundOnOff;
    public static Pixmap buttonPauseStop;
    public static Pixmap buttonGaucheDroite;
    public static Pixmap philUp;
    public static Pixmap philDown;
    public static Pixmap philLeft;
    public static Pixmap philRight;
    public static Pixmap body;
    public static Pixmap bodyWormUp;
    public static Pixmap bodyWormDown;
    public static Pixmap bodyWormLeft;
    public static Pixmap bodyWormRight;
    public static Pixmap bodyShieldUp;
    public static Pixmap bodyShieldDown;
    public static Pixmap bodyShieldLeft;
    public static Pixmap bodyShieldright;
    public static Pixmap blakeUp;
    public static Pixmap blakeDown;
    public static Pixmap blakeLeft;
    public static Pixmap blakeRight;
    public static Pixmap blakeStarsdown;
    public static Pixmap blakeStarsUp;
    public static Pixmap blakeStarsDown;
    public static Pixmap blakeStarsLeft;
    public static Pixmap blakeStarsRight;
    public static Pixmap blakeBipDown;
    public static Pixmap blakeBipUp;
    public static Pixmap blakeBipLeft;
    public static Pixmap blakeBipRight;
    public static Pixmap blakeBinaryDown;
    public static Pixmap blakeBinaryUp;
    public static Pixmap blakeBinaryLeft;
    public static Pixmap blakeBinaryRight;
    public static Pixmap qUp;
    public static Pixmap qDown;
    public static Pixmap qLeft;
    public static Pixmap qRight;
    public static Pixmap qShieldDown;
    public static Pixmap qShieldUp;
    public static Pixmap qShieldLeft;
    public static Pixmap qShieldRight;
    public static Pixmap qWormDown;
    public static Pixmap qWormUp;
    public static Pixmap qWormLeft;
    public static Pixmap qWormRight;
    public static Pixmap choixPerso;
    public static Pixmap vies;
    public static Pixmap choixDifficulte;
    public static Pixmap choixDifficulteDesactive;
    public static Pixmap curseurDifficulte;
    
    public static Pixmap buttons;
    public static Pixmap help1;
    public static Pixmap help2;
    public static Pixmap help3;
    public static Pixmap numbers;
    public static Pixmap ready;
    public static Pixmap pause;
    //public static Pixmap headUp;
    //public static Pixmap headLeft;
    //public static Pixmap headDown;
    //public static Pixmap headRight;
    //public static Pixmap tail;
    //public static Pixmap stain1;
    //public static Pixmap stain2;
    //public static Pixmap stain3;   
    
    public static Pixmap diamond;
    public static Pixmap candy;
    
    public static Pixmap cloud;
    public static Pixmap clouds;
    
    public static Pixmap ovni;
    
    public static Music intro;
    public static Music highscore;
    public static Music level1;
    public static Music gameover;
    
    public static Sound bonus;
    public static Sound superbonus;
    public static Sound dead;
    public static Sound shield;
    public static Sound dudeworm;
    public static Sound less5seconds;
    public static Sound click;
    public static Sound eat;
    public static Sound bitten;
}
